@startuml sequence

actor       Tester     as tester
box "local" #LightBlue
participant TestScript as script
database    HAR        as har
participant "WebDriver+Browser" as browser
participant Proxy      as proxy
end box

box "remote" #LightPink
database    WebServer  as server
end box

tester   -> script     : run it
activate script #FFccFF
script   -> proxy      : start the proxy
activate proxy #ccFFFF
group process test steps
script   -> browser    : navigate to a URL
group for all web resources
browser  -> proxy      : request via proxy
proxy    -> proxy      : log request
proxy    -> server     : send request
server   -> proxy      : reply response
proxy    -> proxy      : log response
proxy    -> browser    : response
end
browser  -> script     : response
script   -> script     : do some tests
end
script   -> proxy      : request HAR
proxy    -> script     : reply HAR
script   -> har        : write HAR into file
script   -> proxy      : stop the proxy
deactivate proxy
script   -> har        : verify the HAR
script   -> tester     : say done
deactivate script
@enduml

