@startuml sequence
actor       Tester     as tester
database    HAR        as file
participant TestScript as script
participant "WebDriver+Browser" as browser
participant Proxy      as proxy
database    WebServer  as server

tester   -> script     : run it
script   -> proxy      : start the proxy
script   -> browser    : navigate to a URL
browser  -> proxy      : request via proxy
proxy    -> proxy      : record request
proxy    -> server     : connect to it
server   -> proxy      : response
proxy    -> proxy      : record response
proxy    -> browser    : response
browser  -> script     : response
script   -> proxy      : request HAR file
proxy    -> script     : reply HAR file
script   -> file       : write
script   -> proxy      : stop the proxy
script   -> tester     : say done
@enduml

